language: python
python:
- '3.4'
env:
  global:
  - GIT_COMMITTER_NAME=channprj
  - GIT_COMMITTER_EMAIL=chann@chann.kr
  - GIT_AUTHOR_NAME=channprj
  - GIT_AUTHOR_EMAIL=chann@chann.kr
  - secure: MkyOLnDgH1m4v0jVjh5v1wtWJ/0MUcGuJgpwav09yEaNy2F2GgkdSWxyAvUVDboRYvd1ahxmI+p9Vf0BCz35M2t8e6ifgKUok0hysj1KAo6Ma6iLILd5zZ33SlXmksy4PcQaihX5QdOotg67M5l0cVQPeRoBI+uwI5g97R/WkX1D6RxnZB7skYXnrTRCiyYUAoCPc8WzdUIacLl1NCvZlSFp2ojyyZzJWrP14tKNFvodETbhS/A9DNBbohqEI3vNXVrdDmBZQzB2Yy319eV/ucOyOl6bD+aZU8giLeVxDgjfTuo9FsUmngflHWtnP4XXmC2QNX729t/kYRTWrylDJ7F0HMNaBZFlg/pHrN2J/gtzP7JEkXKWk/9SpWGg5uqfJmA8EnXZX5dtkeGbyW4B6XdSpEhTcajGR30FQgRffUWR4uwfT/Lz06flRlZffv3iyN2RyTv29i0e4dnvBF3HQLzqt3xPlVy8KoKl/4ab7pY1Y8Ru4MNuwlncMSL8gJPGXEzACQprdfvJQ8QRMX5c4t0HFtjObKoVzvvaol/CyHL9HJCo2qNiAH/XPwZyget95yjeU63SvytzwlHSKhbUZrRN5rRUrQ6VbryC/AJXvJ5zJ6QqYHu27HxsrvVoGJgJGOlorqJTiTP2HJuBo+sFm9Lde5EmX5N2PZiSHdMFQeQ=
before_install:
- git config --global user.email "chann@chann.kr"
- git config --global user.name "CHANN"
install:
- pip install -r requirements.txt -q
before_script:
- git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/channprj/wiki.chann.kr.git
  output
script:
- make publish
after_success:
- cd output
- git add -A
- git commit -m "Contents updated from github using travis-ci."
- git push https://${GH_TOKEN}@github.com/channprj/wiki.chann.kr.git gh-pages --quiet
branches:
  only:
  - master
notifications:
  email: false
